[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "miniauto-pyrear"
version = "0.0.1"
dependencies = [
    "fastapi",
    "uvicorn",
    "opencv-python",
    "numpy",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["miniauto*"]